"""
Authentication endpoints:
  POST /auth/signup   — register a new user
  POST /auth/login    — authenticate & get JWT
  GET  /auth/me       — return current user profile
  GET  /auth/terms    — return full Terms of Service text
"""
from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, EmailStr, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import create_access_token, hash_password, verify_password
from app.db.crud import create_user, get_user_by_email
from app.db.database import get_db
from app.db.models import User
from app.api.deps import get_current_user

router = APIRouter(prefix="/auth", tags=["auth"])


# ── Request / Response schemas ─────────────────────────────────────

class SignupRequest(BaseModel):
    name: str
    email: EmailStr
    password: str
    terms_accepted: bool

    @field_validator("name")
    @classmethod
    def name_not_empty(cls, v: str) -> str:
        v = v.strip()
        if len(v) < 2:
            raise ValueError("Name must be at least 2 characters.")
        if len(v) > 100:
            raise ValueError("Name must be at most 100 characters.")
        return v

    @field_validator("password")
    @classmethod
    def password_strength(cls, v: str) -> str:
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters.")
        return v

    @field_validator("terms_accepted")
    @classmethod
    def must_accept_terms(cls, v: bool) -> bool:
        if not v:
            raise ValueError(
                "You must accept the Terms of Service & Privacy Policy to create an account."
            )
        return v


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class UserResponse(BaseModel):
    id: str
    name: str
    email: str
    created_at: str

    class Config:
        from_attributes = True


class AuthResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


# ── Helper ────────────────────────────────────────────────────────

def _user_response(user: User) -> UserResponse:
    return UserResponse(
        id=str(user.id),
        name=user.name,
        email=user.email,
        created_at=user.created_at.isoformat(),
    )


# ── Endpoints ─────────────────────────────────────────────────────

@router.post("/signup", response_model=AuthResponse, status_code=201)
async def signup(body: SignupRequest, db: AsyncSession = Depends(get_db)):
    """Register a new user account."""
    # Check for duplicate email
    existing = await get_user_by_email(db, body.email)
    if existing:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An account with this email address already exists.",
        )

    user = await create_user(
        db,
        name=body.name.strip(),
        email=body.email,
        hashed_password=hash_password(body.password),
        terms_accepted_at=datetime.now(timezone.utc),
    )

    token = create_access_token(user.id, user.email)
    return AuthResponse(access_token=token, user=_user_response(user))


@router.post("/login", response_model=AuthResponse)
async def login(body: LoginRequest, db: AsyncSession = Depends(get_db)):
    """Authenticate with email and password."""
    user = await get_user_by_email(db, body.email)

    if not user or not verify_password(body.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password.",
        )

    token = create_access_token(user.id, user.email)
    return AuthResponse(access_token=token, user=_user_response(user))


@router.get("/me", response_model=UserResponse)
async def get_me(current_user: User = Depends(get_current_user)):
    """Return the currently authenticated user's profile."""
    return _user_response(current_user)


@router.get("/terms")
async def get_terms():
    """Return the current Terms of Service & Privacy Policy text."""
    return {
        "version": "v1.0",
        "title": "Terms of Service & AI Usage Policy",
        "effective_date": "2026-08-24",
        "sections": [
            {
                "heading": "1. AI-Generated Content & Accuracy",
                "body": (
                    "Research reports are generated by an AI system using real-time web search results. "
                    "While we strive for accuracy, AI-generated content may contain errors, omissions, or "
                    "outdated information. You should independently verify any critical facts, especially "
                    "for medical, legal, financial, or scientific decisions."
                ),
            },
            {
                "heading": "2. Acceptable Use",
                "body": (
                    "You agree not to use this service for automated scraping, bypassing API rate limits, "
                    "generating harmful, illegal, or misleading content, or any purpose that violates "
                    "applicable laws or regulations."
                ),
            },
            {
                "heading": "3. Data & Privacy",
                "body": (
                    "Your research queries and generated reports are stored privately and linked strictly "
                    "to your account. We do not share your data with other users or third parties, except "
                    "as required by law. You may delete your account at any time to remove all associated data."
                ),
            },
            {
                "heading": "4. Acceptance Record",
                "body": (
                    "By creating an account, we record your acceptance of these terms (including the timestamp "
                    "and terms version) to maintain a verifiable record of consent."
                ),
            },
            {
                "heading": "5. Changes to Terms",
                "body": (
                    "We may update these terms from time to time. Continued use of the service after changes "
                    "constitutes acceptance of the updated terms."
                ),
            },
        ],
    }
